### ISSUE TITLE
Planner V8.0.pbit' can't be opened. Either the file is encrypted or corrupted.

### ISSUE THREAD

**Issue by singhnavneet11** [ben-howard/PowerBI-Planner#10]
Hi Ben 

I am trying to use this template and getting "Planner V8.0.pbit' can't be opened. Either the file is encrypted or corrupted" . I am using PowerBI Version: 2.132.1053.0 64-bit (August, 2024). Suggest any fixes/workaround to be done

**Comment by ben-howard** [comment]
I've just opened it.  Power BI Version: 2.132.905.0 64-bit (August 2024).  To open a .pbit file you should go to the File | Import option.  
![image](https://github.com/user-attachments/assets/0b3075b8-ca66-4d94-9606-deea5919a873)

![image](https://github.com/user-attachments/assets/8531b8f8-ef32-438b-a84f-3d1aaac7b63d)

**Comment by singhnavneet11** [comment]
Hi Ben

Thanks for your quick revert , appreciate the same. Unfortunately these option (open by click or import PBIT) are not working for me , may be i am making some mistake or some settings are causing this issue. Attaching screen shot and error log.

suggest if this helps to identify the issue.

[TemplateError.txt](https://github.com/user-attachments/files/16728706/TemplateError.txt)
![Screenshot 2024-08-23 180508](https://github.com/user-attachments/assets/9f9da503-5822-4a6e-bf11-22ab380125fb)

Regards
Navneet Singh

**Comment by ben-howard** [comment]
Hi, try it from your downloads area.   There is no issue with the file from my end, and I downloaded it today.   Same version of Power BI desktop.

![2024-08-23_14-31-17](https://github.com/user-attachments/assets/337dd1d2-f49f-41db-a16a-09314656778d)

**Comment by singhnavneet11** [comment]
Hi Ben,
I was able to sort the issue by reinstalling Power BI with fresh download. I am able to use it now. This is wonderful work accomplished by you and many thanks for sharing the same with us. 

Regards
Navneet Singh
