### ISSUE TITLE
Connecting to Online Source

### ISSUE THREAD

**Issue by erin-aegex** [ben-howard/PowerBI-Planner#3]
Hi Ben,

I am a big fan of the template you created and hope to implement it soon in my company. My goal is to connect a SharePoint Plan from Microsoft Planner to your template so that tasks will be automatically updated, rather than relying on an Excel file that must be exported each time there's a change made to the plan. Currently your template requires a fixed/absolute connection to a file stored on the device. Do you have any suggestions for connecting to SharePoint using your template? 

Many thanks,
Erin Lehmberg
elehmberg@aegex.com
![image](https://user-images.githubusercontent.com/79593889/109031681-f143fe80-7692-11eb-8690-41cad5f424cb.png)

**Comment by brokenthorn** [comment]
First of all, a big fan of your template as well. Thank you a million times for making it open and free to use.

Second of all, I too am looking into integrating this template with a different connector or a more automated way of refreshing the data (like with Microsoft Flow or Sharepoint connector for PowerBI). I will be looking into this in the upcoming months, depending on my available free time, and if I'm able to achieve anything, I will be coming back here to release it for free.

Once again, thank you!

**Comment by ben-howard** [comment]
No problem.  Re Flow etc, I’ve looked into it and simply the actions aren’t there for Planner.  Please share if you can automate this anyway.

**Comment by ben-howard** [comment]
Hi Erin, I've added a .pbit file to this repository which takes files from a sharepoint folder.
