### ISSUE TITLE
How long did it take to build this wonderful template?

### ISSUE THREAD

**Issue by brokenthorn** [ben-howard/PowerBI-Planner#4]
Sorry, I didn't find any other way to ask this, but I'm really curious how long it took to build this wonderful template?

**Comment by ben-howard** [comment]
Hi Paul, it probably took 1-2 days initially,  and then various pages and mods have been added on over the last year or so.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Paul-Sebastian Manole ***@***.***>
Sent: Tuesday, March 16, 2021 2:51:18 PM
To: ben-howard/PowerBI-Planner ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ben-howard/PowerBI-Planner] How long did it take to build this wonderful template? (#4)


Sorry, I didn't find any other way to ask this, but I'm really curious how long it took to build this wonderful template?
