### ISSUE TITLE
Aging report?

### ISSUE THREAD

**Issue by jeffgrossman3000** [ben-howard/PowerBI-Planner#6]
Hi,

_Also a fan here.  Also sorry for abusing the issue system._

I'm looking for a report that uses Starting Date, not Due Date, so I can see how old each card is, grouping them into buckets (e.g., 0-30 days old, 31-60 days old, etc.).  I thought I might be able to make the Gantt Chart do it but no luck.  Is this something I'd have to write or is it already in your excellent .pbit somewhere?

Thanks.

Jeff

**Comment by ben-howard** [comment]
Hi Jeff,
No problem.  It's not in the .pbit (yet), but I've just written this code which will add a calculated column called Ageing Bucket.  It's dax so the column will be recalculated on each refresh. (the code doesn't need formatting, but better if you do!)

Ageing Bucket = 
// Add a calculated column to calculate the age of each task
VAR age = TODAY() - Planner[Start Date]
VAR bucket =  IF (Planner[Start Date], 
                IF (
                    age <= 30, "0-30", 
                        IF ( 
                            age <= 60, "31-60", 
                                IF (
                                    age <= 90, "61-90", 
                                        IF (
                                            age <= 120, "90-120", "120+"
                                        )
                                )
                        )
                    ), BLANK()
                )
    RETURN bucket 

I've attached a .pbix file with the code in, and added another page which should get you started with some ideas for visuals.

![Tasks by age bucket](https://user-images.githubusercontent.com/37085234/127931806-4c5a7054-9962-40a1-a9d7-b875972eedf0.png)
[Planner V7.6.zip](https://github.com/ben-howard/PowerBI-Planner/files/6919934/Planner.V7.6.zip)

**Comment by jeffgrossman3000** [comment]
Brilliant.  Perfect.  Exactly.  Thank you!

I'll offer a little syntactic sweetening:  The buckets will align properly if you add leading spaces to the name.  The spaces are crushed out at render-time so it looks smooth.  I also prefer "not started" to BLANK(), and that can probably be internationalized, too:

VAR bucket = IF (Planner[Start Date],
IF (
age <= 30, "  0-30",
IF (
age <= 60, " 31-60",
IF (
age <= 90, " 61-90",
IF (
age <= 120, " 90-120", "120+"
)
)
)
), "not started"
)

**Comment by jeffgrossman3000** [comment]
When you publish this page I suppose we should close this issue.  For the optics of the thing.  :^)

**Comment by ben-howard** [comment]
😊

**Comment by ben-howard** [comment]
Thanks Geoff.  Updated and everything published.
