### ISSUE TITLE
Latest pbit files will not load in May 2021 release of Power BI Desktop

### ISSUE THREAD

**Issue by donSSC** [ben-howard/PowerBI-Planner#7]
I'm in the government with a managed desktop environment where I cannot install app updates without going through a cumbersome IT Service request process. Are there PBIT files which I can open in the May 2021 version of Power BI Desktop?

Specifically: Version: 2.93.981.0 64-bit (May, 2021)

Thanks

**Comment by ben-howard** [comment]
Hi, I don't keep specific versions to match the Power BI version, but here's a copy of the .pbit which I modified in March 2021.  Hope this helps.


[PlannerFromFolder V7.6.zip](https://github.com/ben-howard/PowerBI-Planner/files/6939712/PlannerFromFolder.V7.6.zip)
